# Generated by Django 5.0.6 on 2024-05-11 07:39

import store.models
import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default='D:\\cs50\\Trenqit\\Firdavs Ecom Fork\\django-react-ecommerce-firdavs\\backend\\media/images/default_placeholder.png', help_text='Upload a product image', upload_to=store.models.upload_path, verbose_name='Image'),
        ),
    ]
